stages:
 - test
 - build
 - deploy

test_users:
 stage: test
 image: python:3
 script:
  - cd $CI_PROJECT_DIR/courseCatalog
  - pip install -r requirements.txt
  - python test_users.py

python-qualitygate:
 stage: test
 image: sonarsource/sonar-scanner-cli
 script:
  - cd $CI_PROJECT_DIR/courseCatalog
  - sonar-scanner -Dsonar.projectKey=courseCatalog -Dsonar.sources=. -Dsonar.host.url=http://sonarqube.34-170-148-91.nip.io -Dsonar.token=sqp_abe1462b781e277a7cee705de42d8b72a3f73ed3


kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${DOCKER_HUB_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/courseCatalog"
      --dockerfile "${CI_PROJECT_DIR}/courseCatalog/Dockerfile"
      --destination "${DOCKER_HUB_IMAGE}:${CI_COMMIT_TAG}"


deploy_gke:
 stage: deploy
 image: google/cloud-sdk
 script:
   - echo "$SERVICE_ACCOUNT_KEY" > key.json
   - gcloud auth activate-service-account --key-file=key.json
   - gcloud config set project root-sanctuary-389315
   - gcloud config set container/cluster sparta-cluster
   - gcloud config set compute/zone us-east1 
   - gcloud container clusters get-credentials sparta-cluster --zone us-central1-c --project root-sanctuary-389315
   - cd $CI_PROJECT_DIR/manifest
   - kubectl apply -f . -n web

